### ISSUE TITLE
Background Maps (WMS) links don't work

### ISSUE THREAD

**Issue by aktentasche** [make-zurich/ogd_geodata#1]
I clicked on http://wms.zh.ch/OrthoZHWMS and http://wms.zh.ch/upwms in README.MD, however Chrome Version 67.0.3396.87 displays following message:

> mapserv(): Web application error. Traditional BROWSE mode requires a TEMPLATE in the WEB section, but none was provided.

Not sure if the server has a problem or if the link is faulty.

**Comment by opendata-zurich** [comment]
Hej @aktentasche, jep, that's because it is a webservice and not just an ordinary link. We've got a description on how one can use WebMapServices here: https://www.stadt-zuerich.ch/portal/de/index/ogd/werkstatt/wms_wmts.html

**Comment by aktentasche** [comment]
Oh right, thanks for clarification!
